name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 2
            persist-credentials: true 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fugashi unidic
          python -m unidic download

      - name: Get added Markdown files
        id: get_md
        run: |
          git fetch origin main
          # 直前のコミットで追加された .md ファイルのみ
          FILES=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^post/.*\.md$' || true)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Update DB for new posts
        run: |
          for f in ${{ steps.get_md.outputs.files }}; do
            echo "Processing $f"
            python main.py "$f"
          done

      - name: Commit updated DB
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add db/data.db
          git commit -m "Update DB for: ${{ steps.get_md.outputs.files }}"
          git push

      - name: Build site
        run: python build.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
